-- 集成测试用 H2（MySQL 兼容模式）建表脚本，结构与 db/init.sql 保持一致
CREATE TABLE sys_dept (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id   BIGINT       NOT NULL DEFAULT 0,
    dept_name   VARCHAR(64)  NOT NULL,
    leader_id   BIGINT,
    sort        INT          NOT NULL DEFAULT 0,
    status      TINYINT      NOT NULL DEFAULT 1,
    remark      VARCHAR(255),
    create_time DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sys_user (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dept_id     BIGINT,
    username    VARCHAR(64)  NOT NULL,
    password    VARCHAR(100) NOT NULL,
    nickname    VARCHAR(64),
    email       VARCHAR(128),
    phone       VARCHAR(32),
    avatar      VARCHAR(255),
    role        VARCHAR(32)  NOT NULL DEFAULT 'USER',
    status      TINYINT      NOT NULL DEFAULT 1,
    create_time DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE wf_process_definition (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    process_name VARCHAR(128) NOT NULL,
    process_key  VARCHAR(64)  NOT NULL UNIQUE,
    status       VARCHAR(16)  NOT NULL DEFAULT 'DRAFT',
    remark       VARCHAR(255),
    create_by    BIGINT,
    update_by    BIGINT,
    create_time  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE wf_process_node (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    process_id      BIGINT       NOT NULL,
    node_type       VARCHAR(20)  NOT NULL DEFAULT 'APPROVAL',
    gateway_mode    VARCHAR(16),
    join_node_id    BIGINT,
    parent_id       BIGINT       NOT NULL DEFAULT 0,
    branch_group    VARCHAR(40),
    condition_expr  VARCHAR(255),
    node_name       VARCHAR(64)  NOT NULL DEFAULT '',
    approver_type   VARCHAR(32),
    approver_ref_id BIGINT,
    sort            INT          NOT NULL DEFAULT 0,
    create_time     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP
);
